### ISSUE TITLE
onBackground for IOS not working?

### ISSUE THREAD

**Issue by Lucesoft** [ekasetiawans/flutter_background_service#331]
I have defined and assigned my onBackground method in IosConfiguration. This method is called periodically by the IOS every 15-20 minutes when the application is backgrounded or completely closed, isn't it? Did I understand correctly? Because it didn't seem to work at all to me, as a result of my actual device and emulator tests.

**Comment by alidemircans** [comment]
is fixed? ı am facing same issue

**Comment by ji-hyun219** [comment]
me too..

**Comment by jaypathak9460** [comment]
facing same issue when User clear the application it stops service as well how to let it continue even after that unable to find the solution for this if anyone have idea let me know also i have added background fetch using XCODE and enable location update ,background fetch and background process also but still not happening (Note:-I am using simulator as do not have any IOS Devices)

**Comment by Sneh-Paghdal** [comment]
I am also having this issue.

**Comment by jrmanes** [comment]
same here guys, is there any updates about it?

**Comment by Wing-Li** [comment]
+1

**Comment by Sneh-Paghdal** [comment]
Nope.

**Comment by curlyeto** [comment]
I also got same issue. Does anyone should that ?
