### ISSUE TITLE
App continues to crash on Android

### ISSUE THREAD

**Issue by zionnite** [ekasetiawans/flutter_background_service#406]
I dont know what its wrong, after app build like within 1-3mins the app will crash immidately 

i'm currently using the latest package `flutter_background_service 5.0.5`

```
D/AndroidRuntime( 5196): Shutting down VM
E/AndroidRuntime( 5196): FATAL EXCEPTION: main
E/AndroidRuntime( 5196): Process: com.com.myapp, PID: 5196
E/AndroidRuntime( 5196): android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{24f2177 u0 com.zioninvasion.prayer_buddy/id.flutter.flutter_background_service.BackgroundService}
E/AndroidRuntime( 5196): 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2104)
E/AndroidRuntime( 5196): 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2075)
E/AndroidRuntime( 5196): 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/AndroidRuntime( 5196): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2369)
E/AndroidRuntime( 5196): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5196): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 5196): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 5196): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 5196): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5196): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 5196): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime( 5196): Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
E/AndroidRuntime( 5196): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1952)
E/AndroidRuntime( 5196): 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1906)
E/AndroidRuntime( 5196): 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
E/AndroidRuntime( 5196): 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1189)
E/AndroidRuntime( 5196): 	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:752)
E/AndroidRuntime( 5196): 	at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.start(FlutterBackgroundServicePlugin.java:82)
E/AndroidRuntime( 5196): 	at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.onMethodCall(FlutterBackgroundServicePlugin.java:121)
E/AndroidRuntime( 5196): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime( 5196): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 5196): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 5196): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 5196): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 5196): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5196): 	... 6 more
I/Process ( 5196): Sending signal. PID: 5196 SIG: 9
```

Please how can this be fix??

**Comment by zionnite** [comment]
No body it's saying anything about this

**Comment by zionnite** [comment]
I was having these issues because i targetted SDK Version 34, by the time i downgraded it to 33 my problem was resolved

**Comment by awaik** [comment]
I have the same issue if I targeting SDK Version 34.
App crashes.

```
type: crash
processUptime: 3030 + 205 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to create service com.pravera.flutter_foreground_task.service.ForegroundService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{7432e38 29602:co..app/u11a180} targetSDK=34
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4722)
 at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8279)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{7432e38 29602:co..app/u11a180} targetSDK=34
 at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
 at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
 at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
 at android.os.Parcel.readParcelable(Parcel.java:4872)
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
 at android.os.Parcel.createException(Parcel.java:3050)
 at android.os.Parcel.readException(Parcel.java:3026)
 at android.os.Parcel.readException(Parcel.java:2968)
 at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6805)
 at android.app.Service.startForeground(Service.java:777)
 at com.pravera.flutter_foreground_task.service.ForegroundService.w(Unknown Source:306)
 at com.pravera.flutter_foreground_task.service.ForegroundService.onCreate(Unknown Source:34)
 at android.app.ActivityThread.handleCreateService(ActivityThread.java:4709)
 ... 11 more
```

So, for now I should use

```
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33
```

**Comment by zionnite** [comment]
change the compileSdkVersion to 33 and rebuild again, i too was facing this
issues

**Comment by nashihu** [comment]
there are 2 exception in this discussion: 

- MissingForegroundServiceTypeException
- ForegroundServiceDidNotStartInTimeException

the first one could be fixed by following [this](https://developer.android.com/about/versions/14/changes/fgs-types-required#permission-for-fgs-type) or downgrading targetSdkVersion to 33 as mentioned before

the second one somehow still occured to me, but it's difficult to reproduce

**Comment by whes1015** [comment]
i have the same issue

**Comment by whes1015** [comment]
change the targetSdkVersion to 33 the problem will be solved

**Comment by bytec-D** [comment]
Since google now required to update all the apps to target the API level 34 so downgrading is not an option now.  i have fixed this issue partially as initial after updating to 34 the app is crashing as soon as launch to i have changed the AndroidManifest as per the plugin documentation .but still i am getting the following crash 


android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{11916d1 u0 uat.com.toop/id.flutter.flutter_background_service.BackgroundService}
E/AndroidRuntime(29357):        at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2104)
E/AndroidRuntime(29357):        at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2075)
E/AndroidRuntime(29357):        at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
E/AndroidRuntime(29357):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2369)
E/AndroidRuntime(29357):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29357):        at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(29357):        at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(29357):        at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(29357):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29357):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(29357):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(29357): Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
E/AndroidRuntime(29357):        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1952)
E/AndroidRuntime(29357):        at android.app.ContextImpl.startForegroundService(ContextImpl.java:1906)
E/AndroidRuntime(29357):        at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
E/AndroidRuntime(29357):        at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1189)
E/AndroidRuntime(29357):        at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:752)
E/AndroidRuntime(29357):        at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.start(FlutterBackgroundServicePlugin.java:82)
E/AndroidRuntime(29357):        at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.onMethodCall(FlutterBackgroundServicePlugin.java:121)
E/AndroidRuntime(29357):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(29357):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(29357):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(29357):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(29357):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(29357):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29357):        ... 6 more

**Comment by m1lmo** [comment]
i have the same issue

**Comment by shinewanna** [comment]
+1, Now Google Policy forced us to use targetSdk 34, so downgrading the targetsdk can't be a patch anymore.

**Comment by tiagomkIS** [comment]
I have the same issue, i've noticed that this problem occurs on the first service initialization/run. After that, the app doesn't crash anymore.

**Comment by UmairSaqibBhutta** [comment]
Facing same issue.

**Comment by Mikelenjilo** [comment]
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException:
  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2216)
  at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2187)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2488)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:243)
  at android.os.Looper.loop (Looper.java:338)
  at android.app.ActivityThread.main (ActivityThread.java:8521)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1064)
Caused by android.app.StackTrace: Last startServiceCommon() call for this service was made here
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:2140)
  at android.app.ContextImpl.startForegroundService (ContextImpl.java:2084)
  at android.content.ContextWrapper.startForegroundService (ContextWrapper.java:830)
  at androidx.core.content.ContextCompat$Api26Impl.startForegroundService (ContextCompat.java:1124)
  at androidx.core.content.ContextCompat.startForegroundService (ContextCompat.java:704)
  at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.start (FlutterBackgroundServicePlugin.java:77)
  at id.flutter.flutter_background_service.FlutterBackgroundServicePlugin.onMethodCall (FlutterBackgroundServicePlugin.java:121)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:267)
  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler (DartMessenger.java:292)
  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0 (DartMessenger.java:319)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)


I'm getting the stack trace above of a crash that is happening in production, anyone knows what can be the cause of it ?
